package LP.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import LP.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.31 12:53:59 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class GenreTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi70 */
  @Test
  public void testRekisteroi70() {    // Genre: 70
    Genre gen1 = new Genre(); 
    assertEquals("From: Genre line: 72", 0, gen1.getIdNro()); 
    gen1.rekisteroi(); 
    Genre gen2 = new Genre(); 
    gen2.rekisteroi(); 
    int n1 = gen1.getIdNro(); 
    int n2 = gen2.getIdNro(); 
    assertEquals("From: Genre line: 78", n2-1, n1); 
  } // Generated by ComTest END
}