package LP.test;
// Generated by ComTest BEGIN
import java.io.File;
import LP.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.28 13:38:40 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class GenretTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta52 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta52() throws SailoException {    // Genret: 52
    Genret genret = new Genret(); 
    Genre gen1 = new Genre(); gen1.defaultGenre(1); 
    Genre gen2 = new Genre(); gen2.defaultGenre(2); 
    Genre gen3 = new Genre(); gen3.defaultGenre(3); 
    Genre gen4 = new Genre(); gen4.defaultGenre(4); 
    Genre gen5 = new Genre(); gen5.defaultGenre(5); 
    String tiedNimi = "testikelmit"; 
    File ftied = new File(tiedNimi+".dat"); 
    ftied.delete(); 
    try {
    genret.lueTiedostosta(tiedNimi); 
    fail("Genret: 64 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    genret.lisaa(gen1); 
    genret.lisaa(gen2); 
    genret.lisaa(gen3); 
    genret.lisaa(gen4); 
    genret.lisaa(gen5); 
    genret.tallenna(); 
    genret = new Genret(); 
    genret.lueTiedostosta(tiedNimi); 
    Iterator<Genre> i = genret.iterator(); 
    assertEquals("From: Genret line: 74", gen1.toString(), i.next().toString()); 
    assertEquals("From: Genret line: 75", gen2.toString(), i.next().toString()); 
    assertEquals("From: Genret line: 76", gen3.toString(), i.next().toString()); 
    assertEquals("From: Genret line: 77", gen4.toString(), i.next().toString()); 
    assertEquals("From: Genret line: 78", gen5.toString(), i.next().toString()); 
    assertEquals("From: Genret line: 79", false, i.hasNext()); 
    genret.lisaa(gen5); 
    genret.tallenna(); 
    assertEquals("From: Genret line: 82", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Genret line: 84", true, fbak.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista149 */
  @Test
  public void testPoista149() {    // Genret: 149
    Genret genret = new Genret(); 
    Genre gen1 = new Genre(); gen1.defaultGenre(1); 
    Genre gen2 = new Genre(); gen2.defaultGenre(2); 
    Genre gen3 = new Genre(); gen3.defaultGenre(3); 
    genret.lisaa(gen1); 
    genret.lisaa(gen2); 
    assertEquals("From: Genret line: 156", false, genret.poista(gen3)); 
    assertEquals("From: Genret line: 157", 2, genret.getLkm()); 
    genret.poista(gen2); 
    assertEquals("From: Genret line: 159", 1, genret.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoistaLevynGenret174 */
  @Test
  public void testPoistaLevynGenret174() {    // Genret: 174
    Genret genret = new Genret(); 
    Genre gen1 = new Genre(); gen1.defaultGenre(1); 
    Genre gen2 = new Genre(); gen2.defaultGenre(2); 
    Genre gen3 = new Genre(); gen3.defaultGenre(2); 
    genret.lisaa(gen1); 
    genret.lisaa(gen2); 
    genret.lisaa(gen3); 
    assertEquals("From: Genret line: 182", 2, genret.poistaLevynGenret(2)); assertEquals("From: Genret line: 182", 1, genret.getLkm()); 
    assertEquals("From: Genret line: 183", 0, genret.poistaLevynGenret(4)); assertEquals("From: Genret line: 183", 1, genret.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator213 */
  @Test
  public void testIterator213() {    // Genret: 213
    Genret genret = new Genret(); 
    Genre gen21 = new Genre(2); genret.lisaa(gen21); 
    Genre gen11 = new Genre(1); genret.lisaa(gen11); 
    Genre gen22 = new Genre(2); genret.lisaa(gen22); 
    Genre gen12 = new Genre(1); genret.lisaa(gen12); 
    Genre gen23 = new Genre(2); genret.lisaa(gen23); 
    Iterator<Genre> i2=genret.iterator(); 
    assertEquals("From: Genret line: 225", gen21, i2.next()); 
    assertEquals("From: Genret line: 226", gen11, i2.next()); 
    assertEquals("From: Genret line: 227", gen22, i2.next()); 
    assertEquals("From: Genret line: 228", gen12, i2.next()); 
    assertEquals("From: Genret line: 229", gen23, i2.next()); 
    try {
    assertEquals("From: Genret line: 230", gen12, i2.next()); 
    fail("Genret: 230 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int jnrot[] = { 2,1,2,1,2} ; 
    for ( Genre gen:genret ) {
    assertEquals("From: Genret line: 236", jnrot[n], gen.getLevyNro()); n++; 
    }
    assertEquals("From: Genret line: 239", 5, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaGenret290 */
  @Test
  public void testAnnaGenret290() {    // Genret: 290
    Genret genret = new Genret(); 
    Genre gen21 = new Genre(2); genret.lisaa(gen21); 
    Genre gen11 = new Genre(1); genret.lisaa(gen11); 
    Genre gen22 = new Genre(2); genret.lisaa(gen22); 
    Genre gen12 = new Genre(1); genret.lisaa(gen12); 
    Genre gen23 = new Genre(2); genret.lisaa(gen23); 
    Genre gen51 = new Genre(5); genret.lisaa(gen51); 
    List<Genre> loytyneet; 
    loytyneet = genret.annaGenret(3); 
    assertEquals("From: Genret line: 303", 0, loytyneet.size()); 
    loytyneet = genret.annaGenret(1); 
    assertEquals("From: Genret line: 305", 2, loytyneet.size()); 
    assertEquals("From: Genret line: 306", true, loytyneet.get(0) == gen11); 
    assertEquals("From: Genret line: 307", true, loytyneet.get(1) == gen12); 
    loytyneet = genret.annaGenret(5); 
    assertEquals("From: Genret line: 309", 1, loytyneet.size()); 
    assertEquals("From: Genret line: 310", true, loytyneet.get(0) == gen51); 
  } // Generated by ComTest END
}