package LP.test;
// Generated by ComTest BEGIN
import LP.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.31 12:56:13 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class GenretTest {


  // Generated by ComTest BEGIN
  /** testIterator71 */
  @Test
  public void testIterator71() {    // Genret: 71
    Genret genret = new Genret(); 
    Genre gen21 = new Genre(2); genret.lisaa(gen21); 
    Genre gen11 = new Genre(1); genret.lisaa(gen11); 
    Genre gen22 = new Genre(2); genret.lisaa(gen22); 
    Genre gen12 = new Genre(1); genret.lisaa(gen12); 
    Genre gen23 = new Genre(2); genret.lisaa(gen23); 
    Iterator<Genre> i2=genret.iterator(); 
    assertEquals("From: Genret line: 83", gen21, i2.next()); 
    assertEquals("From: Genret line: 84", gen11, i2.next()); 
    assertEquals("From: Genret line: 85", gen22, i2.next()); 
    assertEquals("From: Genret line: 86", gen12, i2.next()); 
    assertEquals("From: Genret line: 87", gen23, i2.next()); 
    try {
    assertEquals("From: Genret line: 88", gen12, i2.next()); 
    fail("Genret: 88 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int jnrot[] = { 2,1,2,1,2} ; 
    for ( Genre gen:genret ) {
    assertEquals("From: Genret line: 94", jnrot[n], gen.getLevyNro()); n++; 
    }
    assertEquals("From: Genret line: 97", 5, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaGenret112 */
  @Test
  public void testAnnaGenret112() {    // Genret: 112
    Genret genret = new Genret(); 
    Genre gen21 = new Genre(2); genret.lisaa(gen21); 
    Genre gen11 = new Genre(1); genret.lisaa(gen11); 
    Genre gen22 = new Genre(2); genret.lisaa(gen22); 
    Genre gen12 = new Genre(1); genret.lisaa(gen12); 
    Genre gen23 = new Genre(2); genret.lisaa(gen23); 
    Genre gen51 = new Genre(5); genret.lisaa(gen51); 
    List<Genre> loytyneet; 
    loytyneet = genret.annaGenret(3); 
    assertEquals("From: Genret line: 125", 0, loytyneet.size()); 
    loytyneet = genret.annaGenret(1); 
    assertEquals("From: Genret line: 127", 2, loytyneet.size()); 
    assertEquals("From: Genret line: 128", true, loytyneet.get(0) == gen11); 
    assertEquals("From: Genret line: 129", true, loytyneet.get(1) == gen12); 
    loytyneet = genret.annaGenret(5); 
    assertEquals("From: Genret line: 131", 1, loytyneet.size()); 
    assertEquals("From: Genret line: 132", true, loytyneet.get(0) == gen51); 
  } // Generated by ComTest END
}