package LP.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import LP.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.07 09:39:52 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class GenreTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi71 */
  @Test
  public void testRekisteroi71() {    // Genre: 71
    Genre gen1 = new Genre(); 
    assertEquals("From: Genre line: 73", 0, gen1.getIdNro()); 
    gen1.rekisteroi(); 
    Genre gen2 = new Genre(); 
    gen2.rekisteroi(); 
    int n1 = gen1.getIdNro(); 
    int n2 = gen2.getIdNro(); 
    assertEquals("From: Genre line: 79", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString122 */
  @Test
  public void testToString122() {    // Genre: 122
    Genre gen = new Genre(); 
    gen.parse(" 1 | 2 | Alternative Rock "); 
    assertEquals("From: Genre line: 125", "1|2|Alternative Rock", gen.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse139 */
  @Test
  public void testParse139() {    // Genre: 139
    Genre gen = new Genre(); 
    gen.parse(" 1 | 2 | Alternative Rock "); 
    assertEquals("From: Genre line: 142", 1, gen.getIdNro()); 
    assertEquals("From: Genre line: 143", "1|2|Alternative Rock", gen.toString()); 
    gen.rekisteroi(); 
    int n = gen.getIdNro(); 
    gen.parse("" + (n+20)); 
    gen.rekisteroi(); 
    assertEquals("From: Genre line: 149", n+20+1, gen.getIdNro()); 
    assertEquals("From: Genre line: 150", "" + (n+20+1) + "|2|Alternative Rock", gen.toString()); 
  } // Generated by ComTest END
}