package LP.test;
// Generated by ComTest BEGIN
import java.io.File;
import LP.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.07 09:39:03 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class GenretTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta52 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta52() throws SailoException {    // Genret: 52
    Genret genret = new Genret(); 
    Genre gen1 = new Genre(); gen1.defaultGenre(1); 
    Genre gen2 = new Genre(); gen2.defaultGenre(2); 
    Genre gen3 = new Genre(); gen3.defaultGenre(3); 
    Genre gen4 = new Genre(); gen4.defaultGenre(4); 
    Genre gen5 = new Genre(); gen5.defaultGenre(5); 
    String tiedNimi = "testikelmit"; 
    File ftied = new File(tiedNimi+".dat"); 
    ftied.delete(); 
    try {
    genret.lueTiedostosta(tiedNimi); 
    fail("Genret: 64 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    genret.lisaa(gen1); 
    genret.lisaa(gen2); 
    genret.lisaa(gen3); 
    genret.lisaa(gen4); 
    genret.lisaa(gen5); 
    genret.tallenna(); 
    genret = new Genret(); 
    genret.lueTiedostosta(tiedNimi); 
    Iterator<Genre> i = genret.iterator(); 
    assertEquals("From: Genret line: 74", gen1.toString(), i.next().toString()); 
    assertEquals("From: Genret line: 75", gen2.toString(), i.next().toString()); 
    assertEquals("From: Genret line: 76", gen3.toString(), i.next().toString()); 
    assertEquals("From: Genret line: 77", gen4.toString(), i.next().toString()); 
    assertEquals("From: Genret line: 78", gen5.toString(), i.next().toString()); 
    assertEquals("From: Genret line: 79", false, i.hasNext()); 
    genret.lisaa(gen5); 
    genret.tallenna(); 
    assertEquals("From: Genret line: 82", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Genret line: 84", true, fbak.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator160 */
  @Test
  public void testIterator160() {    // Genret: 160
    Genret genret = new Genret(); 
    Genre gen21 = new Genre(2); genret.lisaa(gen21); 
    Genre gen11 = new Genre(1); genret.lisaa(gen11); 
    Genre gen22 = new Genre(2); genret.lisaa(gen22); 
    Genre gen12 = new Genre(1); genret.lisaa(gen12); 
    Genre gen23 = new Genre(2); genret.lisaa(gen23); 
    Iterator<Genre> i2=genret.iterator(); 
    assertEquals("From: Genret line: 172", gen21, i2.next()); 
    assertEquals("From: Genret line: 173", gen11, i2.next()); 
    assertEquals("From: Genret line: 174", gen22, i2.next()); 
    assertEquals("From: Genret line: 175", gen12, i2.next()); 
    assertEquals("From: Genret line: 176", gen23, i2.next()); 
    try {
    assertEquals("From: Genret line: 177", gen12, i2.next()); 
    fail("Genret: 177 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int jnrot[] = { 2,1,2,1,2} ; 
    for ( Genre gen:genret ) {
    assertEquals("From: Genret line: 183", jnrot[n], gen.getLevyNro()); n++; 
    }
    assertEquals("From: Genret line: 186", 5, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaGenret237 */
  @Test
  public void testAnnaGenret237() {    // Genret: 237
    Genret genret = new Genret(); 
    Genre gen21 = new Genre(2); genret.lisaa(gen21); 
    Genre gen11 = new Genre(1); genret.lisaa(gen11); 
    Genre gen22 = new Genre(2); genret.lisaa(gen22); 
    Genre gen12 = new Genre(1); genret.lisaa(gen12); 
    Genre gen23 = new Genre(2); genret.lisaa(gen23); 
    Genre gen51 = new Genre(5); genret.lisaa(gen51); 
    List<Genre> loytyneet; 
    loytyneet = genret.annaGenret(3); 
    assertEquals("From: Genret line: 250", 0, loytyneet.size()); 
    loytyneet = genret.annaGenret(1); 
    assertEquals("From: Genret line: 252", 2, loytyneet.size()); 
    assertEquals("From: Genret line: 253", true, loytyneet.get(0) == gen11); 
    assertEquals("From: Genret line: 254", true, loytyneet.get(1) == gen12); 
    loytyneet = genret.annaGenret(5); 
    assertEquals("From: Genret line: 256", 1, loytyneet.size()); 
    assertEquals("From: Genret line: 257", true, loytyneet.get(0) == gen51); 
  } // Generated by ComTest END
}