package LP.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import LP.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.31 13:26:28 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjastoTest {


  // Generated by ComTest BEGIN
  /** 
   * testLisaa41 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa41() throws SailoException {    // Kirjasto: 41
    Kirjasto kirjasto = new Kirjasto(); 
    Levy levy1 = new Levy(), levy2 = new Levy(); 
    levy1.rekisteroi(); levy2.rekisteroi(); 
    assertEquals("From: Kirjasto line: 46", 0, kirjasto.getLevyja()); 
    kirjasto.lisaa(levy1); assertEquals("From: Kirjasto line: 47", 1, kirjasto.getLevyja()); 
    kirjasto.lisaa(levy2); assertEquals("From: Kirjasto line: 48", 2, kirjasto.getLevyja()); 
    kirjasto.lisaa(levy1); assertEquals("From: Kirjasto line: 49", 3, kirjasto.getLevyja()); 
    assertEquals("From: Kirjasto line: 50", 3, kirjasto.getLevyja()); 
    assertEquals("From: Kirjasto line: 51", levy1, kirjasto.annaLevy(0)); 
    assertEquals("From: Kirjasto line: 52", levy2, kirjasto.annaLevy(1)); 
    assertEquals("From: Kirjasto line: 53", levy1, kirjasto.annaLevy(2)); 
    try {
    assertEquals("From: Kirjasto line: 54", levy1, kirjasto.annaLevy(3)); 
    fail("Kirjasto: 54 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kirjasto.lisaa(levy1); assertEquals("From: Kirjasto line: 55", 4, kirjasto.getLevyja()); 
    kirjasto.lisaa(levy1); assertEquals("From: Kirjasto line: 56", 5, kirjasto.getLevyja()); 
    try {
    kirjasto.lisaa(levy1); 
    fail("Kirjasto: 57 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaGenret111 */
  @Test
  public void testAnnaGenret111() {    // Kirjasto: 111
    Kirjasto kirjasto = new Kirjasto(); 
    Levy levy1 = new Levy(), levy2 = new Levy(), levy3 = new Levy(); 
    levy1.rekisteroi(); levy2.rekisteroi(); levy3.rekisteroi(); 
    int id1 = levy1.getIdNro(); 
    int id2 = levy2.getIdNro(); 
    Genre gen1 = new Genre(id1); kirjasto.lisaa(gen1); 
    Genre gen2 = new Genre(id1); kirjasto.lisaa(gen2); 
    Genre gen3 = new Genre(id2); kirjasto.lisaa(gen3); 
    Genre gen4 = new Genre(id2); kirjasto.lisaa(gen4); 
    Genre gen5 = new Genre(id2); kirjasto.lisaa(gen5); 
    List<Genre> loytyneet; 
    loytyneet = kirjasto.annaGenret(levy3); 
    assertEquals("From: Kirjasto line: 127", 0, loytyneet.size()); 
    loytyneet = kirjasto.annaGenret(levy1); 
    assertEquals("From: Kirjasto line: 129", 2, loytyneet.size()); 
    assertEquals("From: Kirjasto line: 130", true, loytyneet.get(0) == gen1); 
    assertEquals("From: Kirjasto line: 131", true, loytyneet.get(1) == gen2); 
    loytyneet = kirjasto.annaGenret(levy2); 
    assertEquals("From: Kirjasto line: 133", 3, loytyneet.size()); 
    assertEquals("From: Kirjasto line: 134", true, loytyneet.get(0) == gen3); 
  } // Generated by ComTest END
}