package LP.test;
// Generated by ComTest BEGIN
import java.io.File;
import java.util.Iterator;

import static org.junit.Assert.*;
import org.junit.*;
import LP.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.07 09:56:02 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LevytTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa35 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa35() throws SailoException {    // Levyt: 35
    Levyt levyt = new Levyt(); 
    Levy levy1 = new Levy(), levy2 = new Levy(); 
    assertEquals("From: Levyt line: 39", 0, levyt.getLkm()); 
    levyt.lisaa(levy1); assertEquals("From: Levyt line: 40", 1, levyt.getLkm()); 
    levyt.lisaa(levy2); assertEquals("From: Levyt line: 41", 2, levyt.getLkm()); 
    levyt.lisaa(levy1); assertEquals("From: Levyt line: 42", 3, levyt.getLkm()); 
    assertEquals("From: Levyt line: 43", levy1, levyt.anna(0)); 
    assertEquals("From: Levyt line: 44", levy2, levyt.anna(1)); 
    assertEquals("From: Levyt line: 45", levy1, levyt.anna(2)); 
    assertEquals("From: Levyt line: 46", false, levyt.anna(1) == levy1); 
    assertEquals("From: Levyt line: 47", true, levyt.anna(1) == levy2); 
    try {
    assertEquals("From: Levyt line: 48", levy1, levyt.anna(3)); 
    fail("Levyt: 48 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    levyt.lisaa(levy1); assertEquals("From: Levyt line: 49", 4, levyt.getLkm()); 
    levyt.lisaa(levy1); assertEquals("From: Levyt line: 50", 5, levyt.getLkm()); 
    try {
    levyt.lisaa(levy1); 
    fail("Levyt: 51 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta79 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta79() throws SailoException {    // Levyt: 79
    Levyt levyt = new Levyt(); 
    Levy levy1 = new Levy(), levy2 = new Levy(); 
    levy1.defaultLevy(); 
    levy2.defaultLevy(); 
    String hakemisto = "testielias"; 
    String tiedNimi = hakemisto + "/levyt"; 
    File ftied = new File(tiedNimi+".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    try {
    levyt.lueTiedostosta(tiedNimi); 
    fail("Levyt: 93 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    levyt.lisaa(levy1); 
    levyt.lisaa(levy2); 
    levyt.tallenna(); 
    levyt = new Levyt(); 
    levyt.lueTiedostosta(tiedNimi); 
    Iterator<Levy> i = levyt.iterator(); 
    assertEquals("From: Levyt line: 100", levy1, i.next()); 
    assertEquals("From: Levyt line: 101", levy2, i.next()); 
    assertEquals("From: Levyt line: 102", false, i.hasNext()); 
    levyt.lisaa(levy2); 
    levyt.tallenna(); 
    assertEquals("From: Levyt line: 105", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Levyt line: 107", true, fbak.delete()); 
    assertEquals("From: Levyt line: 108", true, dir.delete()); 
  } // Generated by ComTest END
}