package LP.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import LP.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.31 13:02:29 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LevyTest {


  // Generated by ComTest BEGIN
  /** testGetNimi28 */
  @Test
  public void testGetNimi28() {    // Levy: 28
    Levy levy = new Levy(); 
    levy.defaultLevy(); 
    assertEquals("From: Levy line: 31", "In Rainbows", levy.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi79 */
  @Test
  public void testRekisteroi79() {    // Levy: 79
    Levy levy1 = new Levy(); 
    assertEquals("From: Levy line: 81", 0, levy1.getIdNro()); 
    levy1.rekisteroi(); 
    Levy levy2 = new Levy(); 
    levy2.rekisteroi(); 
    int n1 = levy1.getIdNro(); 
    int n2 = levy2.getIdNro(); 
    assertEquals("From: Levy line: 87", n2-1, n1); 
  } // Generated by ComTest END
}