package LP.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import LP.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.31 13:11:10 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LevytTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa30 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa30() throws SailoException {    // Levyt: 30
    Levyt levyt = new Levyt(); 
    Levy levy1 = new Levy(), levy2 = new Levy(); 
    assertEquals("From: Levyt line: 34", 0, levyt.getLkm()); 
    levyt.lisaa(levy1); assertEquals("From: Levyt line: 35", 1, levyt.getLkm()); 
    levyt.lisaa(levy2); assertEquals("From: Levyt line: 36", 2, levyt.getLkm()); 
    levyt.lisaa(levy1); assertEquals("From: Levyt line: 37", 3, levyt.getLkm()); 
    assertEquals("From: Levyt line: 38", levy1, levyt.anna(0)); 
    assertEquals("From: Levyt line: 39", levy2, levyt.anna(1)); 
    assertEquals("From: Levyt line: 40", levy1, levyt.anna(2)); 
    assertEquals("From: Levyt line: 41", false, levyt.anna(1) == levy1); 
    assertEquals("From: Levyt line: 42", true, levyt.anna(1) == levy2); 
    try {
    assertEquals("From: Levyt line: 43", levy1, levyt.anna(3)); 
    fail("Levyt: 43 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    levyt.lisaa(levy1); assertEquals("From: Levyt line: 44", 4, levyt.getLkm()); 
    levyt.lisaa(levy1); assertEquals("From: Levyt line: 45", 5, levyt.getLkm()); 
    try {
    levyt.lisaa(levy1); 
    fail("Levyt: 46 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}