package LP.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import LP.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.07 09:50:09 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LevyTest {



  // Generated by ComTest BEGIN
  /** testGetNimi29 */
  @Test
  public void testGetNimi29() {    // Levy: 29
    Levy levy = new Levy(); 
    levy.defaultLevy(); 
    assertEquals("From: Levy line: 32", "In Rainbows", levy.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi80 */
  @Test
  public void testRekisteroi80() {    // Levy: 80
    Levy levy1 = new Levy(); 
    assertEquals("From: Levy line: 82", 0, levy1.getIdNro()); 
    levy1.rekisteroi(); 
    Levy levy2 = new Levy(); 
    levy2.rekisteroi(); 
    int n1 = levy1.getIdNro(); 
    int n2 = levy2.getIdNro(); 
    assertEquals("From: Levy line: 88", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString122 */
  @Test
  public void testToString122() {    // Levy: 122
    Levy levy = new Levy(); 
    levy.parse(" 1 | In Rainbows | Radiohead"); 
    assertEquals("From: Levy line: 125", true, levy.toString().startsWith("1|In Rainbows|Radiohead|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse147 */
  @Test
  public void testParse147() {    // Levy: 147
    Levy levy = new Levy(); 
    levy.parse(" 1 | In Rainbows | Radiohead"); 
    assertEquals("From: Levy line: 150", true, levy.toString().startsWith("1|In Rainbows|Radiohead|")); 
    levy.rekisteroi(); 
    int n = levy.getIdNro(); 
    levy.parse(""+(n+20)); 
    levy.rekisteroi(); 
    assertEquals("From: Levy line: 156", n+20+1, levy.getIdNro()); 
  } // Generated by ComTest END
}